### ISSUE TITLE
show one slide

### ISSUE THREAD

**Issue by wireinet** [Neolot/Wordpress.YoutubeCarousel#1]
Hello! You plugin is awesome! Simple and powerful! This is what i searching!
Can you tell me – may i chuse how many slides to show ?
I need to show only one (in sidebar) and three, for example, in the page, Where i can find this values?

**Comment by Neolot** [comment]
Hey!
The plugin uses Jcarousel library. You are free to use any options that this library supports.
Just change ycarousel.js or styles.css.
Jcarousel docs: [https://sorgalla.com/jcarousel/docs](https://sorgalla.com/jcarousel/docs)
